### ISSUE TITLE
ImageNet-trained model?

### ISSUE THREAD

**Issue by ValerioB88** [chung-neuroai-lab/adversarial-manifolds#2]
Hello. As far as I understand, this architecture is the same that currently has the highest [Brain Score ](http://www.brain-score.org/). 

However, it seems that only the version trained on CIFAR10 is accessible here. Is the version achieving the highest Brain-Score also trained only on CIFAR10, or has been trained on ImageNet? If so, can you share the ImageNet-trained version?
Thanks

**Comment by dapello** [comment]
Hello, sorry for the delay -- as you observed, the VOneNet architectures shared here are trained on CIFAR10. The VOneNet architecture trained on ImageNet and submitted to Brainscore is available at the original [VOneNets repository](https://github.com/dicarlolab/vonenet). 

However, the top model on Brainscore is actually the adversarially trained form of VOneNet which has not been publicly released yet, as it's part of on going research. 

Let me know if you have any other questions.

**Comment by ValerioB88** [comment]
Hi Joel,
thanks for your reply. What's the highest brain score  model publicly
available from your lab? voneresnet-50-non_stochastic
<http://www.brain-score.org/model/791>? voneresnet-50
<http://www.brain-score.org/model/676>?
Thanks
Valerio

**Comment by dapello** [comment]
Valerio,
The VOneResNet-50 model which scores third on brain-score is available pretrained through the original VOneNets repository. The VOneResNet-50-non_stochastic is that same architecture but with no stochasticity during training or evaluation -- it can be created quite easily from the VOneNets repo as well. 

I'm going to close this issue now -- if you have trouble with those models please open and issue on the VOneNets repo.

Cheers,
Joel

**Comment by ValerioB88** [comment]
Hi Joel,
All clear, many thanks.
Best,
Valerio
